name: Build and Upload Binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            arch: x64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            arch: arm64
          - os: macos-15
            target: x86_64-apple-darwin
            arch: x64
          - os: macos-15
            target: aarch64-apple-darwin
            arch: arm64
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            arch: x64
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rosetta for macOS x64
        if: runner.os == 'macOS' && matrix.arch == 'x64'
        run: |
          sudo softwareupdate --install-rosetta --agree-to-license

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: difftw-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/difftw*

  create-universal-binary:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: difftw-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release

      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: difftw-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release

      - name: Create Universal Binary
        run: |
          lipo -create target/aarch64-apple-darwin/release/difftw target/x86_64-apple-darwin/release/difftw -output difftw

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: difftw-macos-universal
          path: difftw
